import Head from 'next/head';
import Image from 'next/image';
import { About, Contact, Products, SectionTop, Top } from '../components';
import styles from '../styles/Home.module.css';
import HomeCm from './../components/Home/HomeCm';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Less Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Top />
      <SectionTop title="about" id="about" />
      <About />
      <SectionTop title="contact us" id="contact" />
      <Contact />
      <SectionTop title="products" id="products" />
      <Products />
    </div>
  );
}
